### ISSUE TITLE
Update only "changed" template files

### ISSUE THREAD

**Issue by mcometa** [Polyethylene/gulp-template-mandrill#1]
Is it possible to only update all the changed files in a template directory? What do think is the best approach to it?

**Comment by CalebKester** [comment]
@mcometa I haven't gotten far enough to test this yet, but is this along the lines of what you're looking for? https://github.com/sindresorhus/gulp-changed . I think you'll find some good generic information if you just search on how to do that with gulp, and then apply that to this task.

**Comment by ThamosIO** [comment]
@mcometa @CalebKester closing for lack of follow-up.
