### ISSUE TITLE
Task completes, nothing in mandrill

### ISSUE THREAD

**Issue by CalebKester** [Polyethylene/gulp-template-mandrill#2]
I'm trying to debug why mine isn't working and i'm coming up short.

```
gulp.task('mandrill', function(){
  return gulp.src('mandrill')
    .pipe(gulpTemplateMandrill({
      key: 'blahblahblah'
    }));
});
```

I generated that key from https://mandrillapp.com/settings/index .  I have one html file and a json file under my mandrill folder. Here's the json

```
{
  "name": "Test Gulp2",
  "from_email": "myemail@email.com",
  "from_name": "Caleb",
  "subject": "Thank you",
  "code": "<div>example code</div>",
  "text": "Example text content",
  "publish": false,
  "labels": [
    "Test"
  ]
}
```

And nothing happens when I run `gulp mandrill` Well, it starts and finishes in 12ms.  Any ideas?

**Comment by CalebKester** [comment]
Found out my issue. my gulp.src was wrong.

needed to be `gulp.src('./mandrill/*.html')`

**Comment by ThamosIO** [comment]
Hi, didn't see your issue but I'm glad it works !
